export enum FeatureFlagKey {
  IS_UNIQUE_INDEXES_ENABLED = 'IS_UNIQUE_INDEXES_ENABLED',
  IS_JSON_FILTER_ENABLED = 'IS_JSON_FILTER_ENABLED',
  IS_AI_ENABLED = 'IS_AI_ENABLED',
  IS_COMMAND_MENU_ITEM_ENABLED = 'IS_COMMAND_MENU_ITEM_ENABLED',
  IS_MARKETPLACE_SETTING_TAB_VISIBLE = 'IS_MARKETPLACE_SETTING_TAB_VISIBLE',
  IS_RECORD_PAGE_LAYOUT_EDITING_ENABLED = 'IS_RECORD_PAGE_LAYOUT_EDITING_ENABLED',
  IS_PUBLIC_DOMAIN_ENABLED = 'IS_PUBLIC_DOMAIN_ENABLED',
  IS_EMAILING_DOMAIN_ENABLED = 'IS_EMAILING_DOMAIN_ENABLED',
  IS_JUNCTION_RELATIONS_ENABLED = 'IS_JUNCTION_RELATIONS_ENABLED',
  // ESC fork: the in-product self-onboarding wizard (RM #19873). Deliberately
  // absent from DEFAULT_FEATURE_FLAGS, the dev seeder and PUBLIC_FEATURE_FLAGS,
  // so it reads false for every workspace until an admin turns it on.
  IS_ESC_ONBOARDING_WIZARD_ENABLED = 'IS_ESC_ONBOARDING_WIZARD_ENABLED',
  IS_CONNECTED_ACCOUNT_MIGRATED = 'IS_CONNECTED_ACCOUNT_MIGRATED',
  IS_RICH_TEXT_V1_MIGRATED = 'IS_RICH_TEXT_V1_MIGRATED',
  IS_RECORD_PAGE_LAYOUT_GLOBAL_EDITION_ENABLED = 'IS_RECORD_PAGE_LAYOUT_GLOBAL_EDITION_ENABLED',
  // @deprecated - Migration is complete. Kept for backward compatibility
  // until all workspaces have the flag and the flag can be removed entirely.
  IS_DATASOURCE_MIGRATED = 'IS_DATASOURCE_MIGRATED',
}
